### ISSUE TITLE
Name the type of allImages explicitly?

### ISSUE THREAD

**Issue by gregheo** [DevWithTheHair/Conference-Talks#6]
What's the type of `allImages`? The failure closure had the types explicitly listed; might be nice to do the same so it's easy to look up the response type via google.

https://github.com/DevWithTheHair/Conference-Talks/blob/3e5acb4ea6b1e10e0528f68a8c1d23a4b8651f83/Elementary-Celebrity-Recognition-My-Dear-Watson/SwiftCloudWorkshop2.swift#L67

**Comment by DevWithTheHair** [comment]
The type is `ImagesWithFaces`.

I considered having the type in there, but felt that trying to describe the type system (especially in this case with the Watson SDK) might be a bit much given the expected audience.

**Comment by gregheo** [comment]
It was mostly curiosity on my part, but I guess the Watson SDK isn't the topic of the workshop. Skipping the exact type is probably the right move.
