### ISSUE TITLE
One input image has many images?

### ISSUE THREAD

**Issue by gregheo** [DevWithTheHair/Conference-Talks#8]
Probably a quirk of the API, but if the response variable is `allImages` with `images` with `faces` — how can one input image URL spawn many images?

In actual use will `allImages` always only have a single image?

https://github.com/DevWithTheHair/Conference-Talks/blob/3e5acb4ea6b1e10e0528f68a8c1d23a4b8651f83/Elementary-Celebrity-Recognition-My-Dear-Watson/SwiftCloudWorkshop2.swift#L74

**Comment by DevWithTheHair** [comment]
I view it as a quirk of the API (or at the very least the Swift SDK for Watson Visual Recognition) in the method [detectFaces(inImage:failure:success:)](http://watson-developer-cloud.github.io/swift-sdk/swift-api/services/VisualRecognitionV3/Classes/VisualRecognition.html#/s:19VisualRecognitionV30aB0C11detectFacesySS7inImage_ys5Error_pcSg7failureyAA010ImagesWithE0Vc7successtF)

> success: @escaping (ImagesWithFaces) -> Void)

where `ImagesWithFaces` is 

> public struct ImagesWithFaces: JSONDecodable
public let images: [ImageWithFaces]

and `ImageWithFaces` (singular, not plural!) is

> public struct ImageWithFaces: JSONDecodable
public let faces: [Face]

and finally, `Face` is

> public struct Face: JSONDecodable

which is where we can find the optional `Identity`. 

> public struct Identity: JSONDecodable
public let name: String

Whew!

I believe the reason for this is that they reused the same `success` closure type for a _different_ method [detectFaces(inImageFile:failure:success:)](http://watson-developer-cloud.github.io/swift-sdk/swift-api/services/VisualRecognitionV3/Classes/VisualRecognition.html#/s:19VisualRecognitionV30aB0C11detectFacesy10Foundation3URLV11inImageFile_ys5Error_pcSg7failureyAA010ImagesWithE0Vc7successtF) where the caller can specify _multiple_ images as:
> Upload and detect faces in an image or multiple images in a compressed (.zip) file.

**Comment by gregheo** [comment]
Makes sense. Well, as much sense as Watson can have but your explanation makes sense.

Again, should be OK since the API itself isn't the topic here.
