### ISSUE TITLE
Slides: Reverse word order for consistency

### ISSUE THREAD

**Issue by gregheo** [DevWithTheHair/Conference-Talks#9]
In slide 2, I suggest flipping the word order so it reads "iOS Lead at OfferUp". This will match construction of the following line "iOS Engineer at Simple"

**Comment by DevWithTheHair** [comment]
Makes sense. I'll update.

**Comment by DevWithTheHair** [comment]
Updated in https://github.com/DevWithTheHair/Conference-Talks/pull/10
